<?php
require __DIR__.'/config.php';

function runSql($pdo, $sql, $params = []) {
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $stmt;
}

// Read
$equipments = runSql($pdo, 'SELECT * FROM equipment ORDER BY equipment_id')->fetchAll();

// Add / Edit
$mode  = $_GET['mode'] ?? 'add';
$id    = $_GET['id'] ?? null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $property_no   = $_POST['property_no'] ?? '';
    $equipment_name = $_POST['equipment_name'] ?? '';
    $quantity      = (int)($_POST['quantity_available'] ?? 0);

    if ($mode === 'add') {
        $sql = "INSERT INTO equipment (property_no, equipment_name, quantity_available) VALUES (:pn, :en, :qa)";
        runSql($pdo, $sql, [':pn'=>$property_no, ':en'=>$equipment_name, ':qa'=>$quantity]);
    } else {
        $sql = "UPDATE equipment SET property_no=:pn, equipment_name=:en, quantity_available=:qa WHERE equipment_id=:id";
        runSql($pdo, $sql, [':pn'=>$property_no, ':en'=>$equipment_name, ':qa'=>$quantity, ':id'=>$id]);
    }
    header('Location: equipment.php');
    exit;
}

// Delete
if (isset($_GET['del'])) {
    runSql($pdo, 'DELETE FROM equipment WHERE equipment_id=:id', [':id'=>$_GET['del']]);
    header('Location: equipment.php');
    exit;
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Equipment</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">

<nav class="navbar navbar-expand-lg navbar-dark bg-secondary mb-4">
  <div class="container">
    <a class="navbar-brand" href="index.php">Borrow‑Equipment Manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav3">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav3">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item"><a class="nav-link" href="index.php">Dashboard</a></li>
        <li class="nav-item"><a class="nav-link" aria-current="page">Equipment</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">

  <h2 class="mt-4">Equipment List</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Property No</th>
        <th>Equipment Name</th>
        <th>Qty Available</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($equipments as $e): ?>
      <tr>
        <td><?php echo htmlspecialchars($e['equipment_id']); ?></td>
        <td><?php echo htmlspecialchars($e['property_no']); ?></td>
        <td><?php echo htmlspecialchars($e['equipment_name']); ?></td>
        <td><?php echo htmlspecialchars($e['quantity_available']); ?></td>
        <td>
          <a class="btn btn-sm btn-warning" href="?mode=edit&id=<?php echo $e['equipment_id']; ?>">Edit</a>
          <form class="d-inline" method="post" action="?mode=del&id=<?php echo $e['equipment_id']; ?>" onsubmit="return confirm('Delete this equipment?');">
            <button class="btn btn-sm btn-danger" type="submit">Del</button>
          </form>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>

  <h2 class="mt-4"> <?php echo $mode === 'add' ? 'Add New Equipment' : 'Edit Equipment'; ?> </h2>
  <form method="post" class="row g-3">
    <input type="hidden" name="id" value="<?php echo $id ?? ''; ?>">
    <div class="col-md-6">
      <label class="form-label">Property No <span class="text-danger">*</span></label>
      <input type="text" name="property_no" class="form-control" required>
    </div>
    <div class="col-md-6">
      <label class="form-label">Equipment Name <span class="text-danger">*</span></label>
      <input type="text" name="equipment_name" class="form-control" required>
    </div>
    <div class="col-md-4">
      <label class="form-label">Quantity Available <span class="text-danger"> (≥0)</span></label>
      <input type="number" name="quantity_available" class="form-control" min="0" required>
    </div>
    <div class="col-12">
      <button type="submit" class="btn btn-primary">Save</button>
      <a class="btn btn-secondary" href="equipment.php">Cancel</a>
    </div>
  </form>

</div>

<footer class="mt-5 text-center text-muted small">Generated by PHP‑Bootstrap CRUD UI</footer>

</body>
</html>